steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/procurement-backend:$COMMIT_SHA', '.']
    dir: 'procure/procurement'

# Push the image to Container Registry
images:
  - 'gcr.io/$PROJECT_ID/procurement-backend:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
